
package mil.navy.med.dzreg.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import mil.navy.med.dzreg.types.AckType;
import mil.navy.med.dzreg.types.ObjectFactory;
import mil.navy.med.dzreg.types.PersonRegistryProfileRequestType;
import mil.navy.med.dzreg.types.PersonRegistryProfileResponseType;
import mil.navy.med.dzreg.types.RegisterPersonRequestType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "RegistriesServicePortType", targetNamespace = "urn:mil:navy:med:dzreg:service")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RegistriesServicePortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns mil.navy.med.dzreg.types.PersonRegistryProfileResponseType
     */
    @WebMethod(operationName = "GetRegistryProfile", action = "urn:GetRegistryProfile")
    @WebResult(name = "PersonRegistryProfileResponse", targetNamespace = "urn:mil:navy:med:dzreg:types", partName = "parameters")
    public PersonRegistryProfileResponseType getRegistryProfile(
        @WebParam(name = "PersonRegistryProfileRequest", targetNamespace = "urn:mil:navy:med:dzreg:types", partName = "parameters")
        PersonRegistryProfileRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns mil.navy.med.dzreg.types.AckType
     */
    @WebMethod(operationName = "Register", action = "urn:Register")
    @WebResult(name = "ResponseAck", targetNamespace = "urn:mil:navy:med:dzreg:types", partName = "parameters")
    public AckType register(
        @WebParam(name = "RegisterPersonRequest", targetNamespace = "urn:mil:navy:med:dzreg:types", partName = "parameters")
        RegisterPersonRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns mil.navy.med.dzreg.types.AckType
     */
    @WebMethod(operationName = "Unregister", action = "urn:Unregister")
    @WebResult(name = "ResponseAck", targetNamespace = "urn:mil:navy:med:dzreg:types", partName = "parameters")
    public AckType unregister(
        @WebParam(name = "UnregisterPersonRequest", targetNamespace = "urn:mil:navy:med:dzreg:types", partName = "parameters")
        RegisterPersonRequestType parameters);

}
