
package mil.navy.med.dzreg.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RegistriesService", targetNamespace = "urn:mil:navy:med:dzreg:service", wsdlLocation = "/home/nhin/KMR/Properties/wsdl")
public class RegistriesService
    extends Service
{

    private final static URL REGISTRIESSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(mil.navy.med.dzreg.service.RegistriesService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = mil.navy.med.dzreg.service.RegistriesService.class.getResource(".");
            url = new URL(baseUrl, "/home/nhin/KMR/Properties/wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: '/home/nhin/KMR/Properties/wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        REGISTRIESSERVICE_WSDL_LOCATION = url;
    }

    public RegistriesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistriesService() {
        super(REGISTRIESSERVICE_WSDL_LOCATION, new QName("urn:mil:navy:med:dzreg:service", "RegistriesService"));
    }

    /**
     * 
     * @return
     *     returns RegistriesServicePortType
     */
    @WebEndpoint(name = "RegistriesServicePort")
    public RegistriesServicePortType getRegistriesServicePort() {
        return super.getPort(new QName("urn:mil:navy:med:dzreg:service", "RegistriesServicePort"), RegistriesServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegistriesServicePortType
     */
    @WebEndpoint(name = "RegistriesServicePort")
    public RegistriesServicePortType getRegistriesServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:mil:navy:med:dzreg:service", "RegistriesServicePort"), RegistriesServicePortType.class, features);
    }

}
