//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.30 at 05:30:59 PM PDT 
//


package org.socraticgrid.presentationservices.utils.factModels;

import java.util.ArrayList;
import java.util.List;


public class Facts {

    //REQUIRED ATTRIBUTES
    protected String displayCode;
    protected String code;
    protected String codeSystemName;
    protected String codeSystemCode;
    protected List<String> hoverTexts;
    protected String itemId;
    protected String status;

    //PROBLEMS LIST ATTRIBUTES
    protected String lastRecordedDate;
    protected String problem;
    protected String onset;
    protected String acuity;
    protected String facilicy;
    //------------------------
    protected String diagnosis;
    protected String newCode;
    protected String description;

    //PROBLEMS DETAILS ATTRIBUTES
    protected String drugClass;
    protected String example;
    protected String utilization;
    protected String d90Days;
    protected String d180Days;
    protected String d270Days;


    //MEDICATIONS LIST ATTRIBUTES
    protected String orderDate;
    protected String medication;
    protected String sig;
    protected String formulation;
    protected String schedule;
    protected String unit;
    protected String dose;
    protected String route;
    protected String frequency;
    protected String duration;
    protected String quantity;
    protected String refills;
    protected String prescriber;
    protected String orderExpireDate;
    //protected String drugClass; //NOTE: ALREADY DECLARED
    protected String drugClassCode;
    protected String drugClassCodeSystem;

    //MEDICATIONS DETAILS ATTRIBUTES
    protected String title;
    protected List<String> items;
/*
     * {
 Ê"patientDataFact": {
 Ê Ê"-xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
 Ê Ê"-xsi:noNamespaceSchemaLocation": "C:/Users/JERRYG~1/Dropbox/Cognitive/CDS/JSONFact_Demographic.xsd",
 Ê Ê"facts": {
 Ê Ê Ê"patientId": "100013",
 Ê Ê Ê"contactId": "ONEHUNDRED,PATIENT",
 Ê Ê Ê"name": "ONEHUNDRED,PATIENT",
 Ê Ê Ê"lastName": "ONEHUNDRED",
 Ê Ê Ê"firstName": "PATIENT",
 Ê Ê Ê"age": "78",
 Ê Ê Ê"gender": "M",
 Ê Ê Ê"address": "Any Street",
 Ê Ê Ê"city": "Any Town",
 Ê Ê Ê"state": "WEST VIRGINIA",
 Ê Ê Ê"dateOfBirth": "1935-04-07",
 Ê Ê Ê"ssn": "666-00-0100",
 Ê Ê Ê"medicalRecordNo": "11000",
 Ê Ê Ê"primaryDoctor": "Not Mapped",
 Ê Ê Ê"patientStatus": "Unknown",
 Ê Ê Ê"emergencyContact": "VETERAN,BROTHER"
 Ê Ê}
 Ê}
}
     *
     */
    // DEMOGRAPHICS LIST ATTRIBUTES
    protected String name;
    protected int age;
    protected String dateOfBirth;
    protected String gender;
    protected String contactId;
    protected String lastName;
    protected String firstName;
    protected String address;
    protected String city;
    protected String state;
    protected String ssn;
    protected String medicalRecordNo;
    protected String primaryDoctor;
    protected String patientStatus;
    protected String emergencyContact; //patientId value of the person.
    protected String patientId;




    /**
     * Gets the value of the orderDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderDate() {
        return orderDate;
    }

    /**
     * Sets the value of the orderDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderDate(String value) {
        this.orderDate = value;
    }

    /**
     * Gets the value of the medication property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedication() {
        return medication;
    }

    /**
     * Sets the value of the medication property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedication(String value) {
        this.medication = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the codeSystemName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeSystemName() {
        return codeSystemName;
    }

    /**
     * Sets the value of the codeSystemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeSystemName(String value) {
        this.codeSystemName = value;
    }

    /**
     * Gets the value of the codeSystemCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeSystemCode() {
        return codeSystemCode;
    }

    /**
     * Sets the value of the codeSystemCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeSystemCode(String value) {
        this.codeSystemCode = value;
    }

    /**
     * Gets the value of the sig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSig() {
        return sig;
    }

    /**
     * Sets the value of the sig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSig(String value) {
        this.sig = value;
    }

    /**
     * Gets the value of the formulation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormulation() {
        return formulation;
    }

    /**
     * Sets the value of the formulation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormulation(String value) {
        this.formulation = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnit(String value) {
        this.unit = value;
    }

    /**
     * Gets the value of the dose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDose() {
        return dose;
    }

    /**
     * Sets the value of the dose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDose(String value) {
        this.dose = value;
    }

    /**
     * Gets the value of the route property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoute() {
        return route;
    }

    /**
     * Sets the value of the route property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoute(String value) {
        this.route = value;
    }

    /**
     * Gets the value of the frequency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrequency() {
        return frequency;
    }

    /**
     * Sets the value of the frequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrequency(String value) {
        this.frequency = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDuration(String value) {
        this.duration = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuantity(String value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the refills property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefills() {
        return refills;
    }

    /**
     * Sets the value of the refills property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefills(String value) {
        this.refills = value;
    }

    /**
     * Gets the value of the prescriber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrescriber() {
        return prescriber;
    }

    /**
     * Sets the value of the prescriber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrescriber(String value) {
        this.prescriber = value;
    }

    /**
     * Gets the value of the orderExpireDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderExpireDate() {
        return orderExpireDate;
    }

    /**
     * Sets the value of the orderExpireDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderExpireDate(String value) {
        this.orderExpireDate = value;
    }

    /**
     * Gets the value of the hoverTexts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hoverTexts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHoverTexts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getHoverTexts() {
        if (hoverTexts == null) {
            hoverTexts = new ArrayList<String>();
        }
        return this.hoverTexts;
    }

    /**
     * Gets the value of the itemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * Sets the value of the itemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemId(String value) {
        this.itemId = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }


    public String getTitle()                 { return this.title; }
    public void setTitle(String s)           { this.title = s; }

    /**
     * Gets the value of the items property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the items property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItems().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     *
     *
     */
    public List<String> getItems() {
        if (this.items == null) {
            this.items = new ArrayList<String>();
        }
        return this.items;
    }


    // PROBLEMS LIST ATTRIBUTES
    public String getLastRecordedDate()        { return this.lastRecordedDate; }
    public String getProblem()                 { return this.problem; }
    public String getOnset()                   { return this.onset; }
    public String getAcuity()                  { return this.acuity; }
    public String getFacility()                { return this.facilicy; }
    public String getDiagnosis()               { return this.diagnosis; }
    public String getDescription()             { return this.description; }
    public String getNewCode()                 { return this.newCode; }
    public String getDisplayCode()             { return this.displayCode; }
    //------------------------
    public void setLastRecordedDate(String s)  { this.lastRecordedDate = s; }
    public void setProblem(String s)           { this.problem = s; }
    public void setOnset(String s)             { this.onset = s; }
    public void setAcuity(String s)            { this.acuity = s; }
    public void setFacility(String s)          { this.facilicy = s; }
    public void setDiagnosis(String s)         { this.diagnosis = s; }
    public void setDescription(String s)       { this.description = s; }
    public void setNewCode(String s)           { this.newCode = s; }
    public void setDisplayCode(String s)       { this.displayCode = s; }

    // PROBLEMS DETAILS ATTRIBUTES
    public String getDrugClass()               { return this.drugClass; }
    public String getExample()                 { return this.example; }
    public String getUtilization()             { return this.utilization; }
    public String getD90Days()                 { return this.d90Days; }
    public String getD180Days()                { return this.d180Days; }
    public String getD2700Days()               { return this.d270Days; }
    //------------------------
    public void setDrugClass(String s)         { this.drugClass = s; }
    public void setExample(String s)           { this.example = s; }
    public void setUtilization(String s)       { this.utilization = s; }
    public void setD90Days(String s)           { this.d90Days = s; }
    public void setD180Days(String s)          { this.d180Days = s; }
    public void setD270Days(String s)          { this.d270Days = s; }

    // MEDICATION LIST ATTRIBUTES

    public String getSchedule()               { return this.schedule; }
    public void setSchedule(String s)         { this.schedule = s; }


    // DEMOGRAPHICS LIST ATTRIBUTES
    public String getName()                    { return this.name; }
    public int getAge()                        { return this.age; }
    public String getDateOfBirth()             { return this.dateOfBirth; }
    public String getGender()                  { return this.gender; }
    public String getContactId()               { return this.contactId; }
    public String getLastName()                { return this.lastName; }
    public String getFirstName()               { return this.firstName; }
    public String getAddress()                 { return this.address; }
    public String getCity()                    { return this.city; }
    public String getState()                   { return this.state; }
    public String getSSN()                     { return this.ssn; }
    public String getMedicalRecordNo()         { return this.medicalRecordNo; }
    public String getPrimaryDoctor()           { return this.primaryDoctor; }
    public String getPatientStatus()           { return this.patientStatus; }
    public String getEmergencyContact()        { return this.emergencyContact; }
    public String getPatientId()               { return this.patientId; }
    //------------------------
    public void setName(String s)              { this.name = s; }
    public void setAge(int i)                  { this.age = i; }
    public void setDateOfBirth(String s)       { this.dateOfBirth = s; }
    public void setGender(String s)            { this.gender = s; }
    public void setContactId(String s)         { this.contactId = s; }
    public void setLastName(String s)          { this.lastName = s; }
    public void setFirstName(String s)         { this.firstName = s; }
    public void setAddress(String s)           { this.address = s; }
    public void setCity(String s)              { this.city = s; }
    public void setState(String s)             { this.state = s; }
    public void setSSN(String s)               { this.ssn = s; }
    public void setMedicalRecordNo(String s)   { this.medicalRecordNo = s; }
    public void setPrimaryDoctor(String s)     { this.primaryDoctor = s; }
    public void setPatientStatus(String s)     { this.patientStatus = s; }
    public void setEmergencyContact(String s)  { this.emergencyContact = s; }
    public void setPatientId(String s)         { this.patientId = s; }

}
