//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.30 at 05:30:59 PM PDT 
//


package org.socraticgrid.presentationservices.utils.factModels;

public class GetPatientDataFactObject
{
    protected PatientDataFact patientDataFact;

    public GetPatientDataFactObject() {}
    
    public PatientDataFact getpatientDataFact() {return this.patientDataFact; }

    public void setpatientDataFact(PatientDataFact p) { this.patientDataFact = p; }
}
