
package gov.va.medora.mdws.emrsvc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EmrSvcHttpGet", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmrSvcHttpGet {


    /**
     * Get lab test description text
     * 
     * @param identifierString
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getLabTestDescription(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "identifierString")
        String identifierString);

    /**
     * Get a list of lab tests for subsequent call to get test description
     * 
     * @param target
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedLabTestArrays
     */
    @WebMethod
    @WebResult(name = "TaggedLabTestArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedLabTestArrays getLabTests(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "target")
        String target);

    /**
     * Get patient associates (NOK, caregiver, etc.)
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedPatientAssociateArrays
     */
    @WebMethod
    @WebResult(name = "TaggedPatientAssociateArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedPatientAssociateArrays getPatientAssociates();

    /**
     * Get patient's adhoc health summary by display name from all connected VistAs.
     * 
     * @param displayName
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getAdhocHealthSummaryByDisplayName(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "displayName")
        String displayName);

    /**
     * Get patient's IDs from the session's base connection (i.e. from your local site/authenticated site)
     * 
     * @param idType
     * @param patientId
     * @param sitecode
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getCorrespondingIds(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "sitecode")
        String sitecode,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "patientId")
        String patientId,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "idType")
        String idType);

    /**
     * Get all VHA sites
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.RegionArray
     */
    @WebMethod
    @WebResult(name = "RegionArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public RegionArray getVHA();

    /**
     * Get all VHA sites in a VISN
     * 
     * @param regionId
     * @return
     *     returns gov.va.medora.mdws.emrsvc.RegionTO
     */
    @WebMethod
    @WebResult(name = "RegionTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public RegionTO getVISN(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "regionId")
        String regionId);

    /**
     * Connect to a single VistA system.
     * 
     * @param sitelist
     * @return
     *     returns gov.va.medora.mdws.emrsvc.DataSourceArray
     */
    @WebMethod
    @WebResult(name = "DataSourceArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public DataSourceArray connect(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "sitelist")
        String sitelist);

    /**
     * Log onto a single VistA system.
     * 
     * @param pwd
     * @param username
     * @param context
     * @return
     *     returns gov.va.medora.mdws.emrsvc.UserTO
     */
    @WebMethod
    @WebResult(name = "UserTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public UserTO login(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "username")
        String username,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pwd")
        String pwd,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "context")
        String context);

    /**
     * Disconnect from single Vista system.
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray disconnect();

    /**
     * Disconnect from remote Vista systems.
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray disconnectRemoteSites();

    /**
     * Use when switching patient lookup sites.
     * 
     * @param pwd
     * @param userSitecode
     * @param context
     * @param ssn
     * @param userName
     * @param sitelist
     * @param duz
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray visit(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pwd")
        String pwd,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "sitelist")
        String sitelist,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "userSitecode")
        String userSitecode,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "userName")
        String userName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "DUZ")
        String duz,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "SSN")
        String ssn,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "context")
        String context);

    /**
     * Call when launching from CPRS Tools menu: connects, authenticates, selects patient.
     * 
     * @param sitecode
     * @param pwd
     * @param duz
     * @param dfn
     * @return
     *     returns gov.va.medora.mdws.emrsvc.PersonsTO
     */
    @WebMethod
    @WebResult(name = "PersonsTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public PersonsTO cprsLaunch(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pwd")
        String pwd,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "sitecode")
        String sitecode,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "DUZ")
        String duz,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "DFN")
        String dfn);

    /**
     * Lookup a CPRS-enabled user
     * 
     * @param target
     * @return
     *     returns gov.va.medora.mdws.emrsvc.UserArray
     */
    @WebMethod
    @WebResult(name = "UserArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public UserArray cprsUserLookup(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "target")
        String target);

    /**
     * Match patients at logged in site. Accepts: SSN, 'LAST,FIRST', A1234 (Last name initial + last four SSN)
     * 
     * @param target
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedPatientArrays
     */
    @WebMethod
    @WebResult(name = "TaggedPatientArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedPatientArrays match(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "target")
        String target);

    /**
     * Select a patient at logged in site. DFN is the IEN of the patient
     * 
     * @param dfn
     * @return
     *     returns gov.va.medora.mdws.emrsvc.PatientTO
     */
    @WebMethod
    @WebResult(name = "PatientTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public PatientTO select(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "DFN")
        String dfn);

    /**
     * Setup patient's remote sites for querying.
     * 
     * @param appPwd
     * @return
     *     returns gov.va.medora.mdws.emrsvc.SiteArray
     */
    @WebMethod
    @WebResult(name = "SiteArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public SiteArray setupMultiSiteQuery(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "appPwd")
        String appPwd);

    /**
     * Get patient confidentiality from all connected sites.
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getConfidentiality();

    /**
     * Issue patient confidentiality bulletin to all connected sites.
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray issueConfidentialityBulletin();

    /**
     * Get latest vitals from all connected VistAs
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedVitalSignArrays
     */
    @WebMethod
    @WebResult(name = "TaggedVitalSignArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedVitalSignArrays getLatestVitalSigns();

    /**
     * Get patient's vital signs.
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedVitalSignSetArrays
     */
    @WebMethod
    @WebResult(name = "TaggedVitalSignSetArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedVitalSignSetArrays getVitalSigns();

    /**
     * Get allergies from all connected VistAs
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedAllergyArrays
     */
    @WebMethod
    @WebResult(name = "TaggedAllergyArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedAllergyArrays getAllergies();

    /**
     * Get radiology reports from all connected VistAs
     * 
     * @param fromDate
     * @param toDate
     * @param nrpts
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedRadiologyReportArrays
     */
    @WebMethod
    @WebResult(name = "TaggedRadiologyReportArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedRadiologyReportArrays getRadiologyReports(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nrpts")
        String nrpts);

    /**
     * Get surgery reports from all connected VistAs
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedSurgeryReportArrays
     */
    @WebMethod
    @WebResult(name = "TaggedSurgeryReportArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedSurgeryReportArrays getSurgeryReports();

    /**
     * Get text for a certain surgery report
     * 
     * @param siteId
     * @param rptId
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TextTO
     */
    @WebMethod
    @WebResult(name = "TextTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TextTO getSurgeryReportText(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "siteId")
        String siteId,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "rptId")
        String rptId);

    /**
     * Get surgery reports from all connected VistAs
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedSurgeryReportArrays
     */
    @WebMethod
    @WebResult(name = "TaggedSurgeryReportArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedSurgeryReportArrays getSurgeryReportsWithText();

    /**
     * Get problem list from all connected VistAs
     * 
     * @param type
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedProblemArrays
     */
    @WebMethod
    @WebResult(name = "TaggedProblemArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedProblemArrays getProblemList(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "type")
        String type);

    /**
     * Get outpatient medications from all connected VistAs
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedMedicationArrays
     */
    @WebMethod
    @WebResult(name = "TaggedMedicationArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedMedicationArrays getOutpatientMeds();

    /**
     * Get IV medications from all connected VistAs
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedMedicationArrays
     */
    @WebMethod
    @WebResult(name = "TaggedMedicationArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedMedicationArrays getIvMeds();

    /**
     * Get Inpatient for Outpatient medications from all connected VistAs
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedMedicationArrays
     */
    @WebMethod
    @WebResult(name = "TaggedMedicationArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedMedicationArrays getImoMeds();

    /**
     * Get unit dose medications from all connected VistAs
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedMedicationArrays
     */
    @WebMethod
    @WebResult(name = "TaggedMedicationArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedMedicationArrays getUnitDoseMeds();

    /**
     * Get non-VA medications from all connected VistAs
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedMedicationArrays
     */
    @WebMethod
    @WebResult(name = "TaggedMedicationArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedMedicationArrays getOtherMeds();

    /**
     * Get all medications from all connected VistAs
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedMedicationArrays
     */
    @WebMethod
    @WebResult(name = "TaggedMedicationArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedMedicationArrays getAllMeds();

    /**
     * Get medication detail from a single connected VistA.
     * 
     * @param siteId
     * @param medId
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TextTO
     */
    @WebMethod
    @WebResult(name = "TextTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TextTO getMedicationDetail(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "siteId")
        String siteId,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "medId")
        String medId);

    /**
     * Get signed note metadata from all connected VistAs
     * 
     * @param fromDate
     * @param nNotes
     * @param toDate
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedNoteArrays
     */
    @WebMethod
    @WebResult(name = "TaggedNoteArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedNoteArrays getSignedNotes(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nNotes")
        String nNotes);

    /**
     * Get unsigned note metadata from all connected VistAs
     * 
     * @param fromDate
     * @param nNotes
     * @param toDate
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedNoteArrays
     */
    @WebMethod
    @WebResult(name = "TaggedNoteArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedNoteArrays getUnsignedNotes(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nNotes")
        String nNotes);

    /**
     * Get uncosigned note metadata from all connected VistAs
     * 
     * @param fromDate
     * @param nNotes
     * @param toDate
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedNoteArrays
     */
    @WebMethod
    @WebResult(name = "TaggedNoteArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedNoteArrays getUncosignedNotes(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nNotes")
        String nNotes);

    /**
     * Get a note from a single connected VistA.
     * 
     * @param siteId
     * @param noteId
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TextTO
     */
    @WebMethod
    @WebResult(name = "TextTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TextTO getNote(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "siteId")
        String siteId,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "noteId")
        String noteId);

    /**
     * Get notes with text from all connected VistAs.
     * 
     * @param fromDate
     * @param nNotes
     * @param toDate
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedNoteArrays
     */
    @WebMethod
    @WebResult(name = "TaggedNoteArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedNoteArrays getNotesWithText(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nNotes")
        String nNotes);

    /**
     * Get discharge summaries from all connected VistAs.
     * 
     * @param fromDate
     * @param nNotes
     * @param toDate
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedNoteArrays
     */
    @WebMethod
    @WebResult(name = "TaggedNoteArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedNoteArrays getDischargeSummaries(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nNotes")
        String nNotes);

    /**
     * Get patient's current consults.
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedConsultArrays
     */
    @WebMethod
    @WebResult(name = "TaggedConsultArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedConsultArrays getConsultsForPatient();

    /**
     * Get patient's appointments.
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedAppointmentArrays
     */
    @WebMethod
    @WebResult(name = "TaggedAppointmentArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedAppointmentArrays getAppointments();

    /**
     * Get note for appointment.
     * 
     * @param siteId
     * @param apptId
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TextTO
     */
    @WebMethod
    @WebResult(name = "TextTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TextTO getAppointmentText(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "siteId")
        String siteId,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "apptId")
        String apptId);

    /**
     * Get patient's clinical warnings.
     * 
     * @param fromDate
     * @param toDate
     * @param nrpts
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getClinicalWarnings(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nrpts")
        String nrpts);

    /**
     * Get patient's advance directives.
     * 
     * @param fromDate
     * @param toDate
     * @param nrpts
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getAdvanceDirectives(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nrpts")
        String nrpts);

    /**
     * Get patient's crisis notes.
     * 
     * @param fromDate
     * @param toDate
     * @param nrpts
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getCrisisNotes(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nrpts")
        String nrpts);

    /**
     * Get patient's immunizations.
     * 
     * @param fromDate
     * @param toDate
     * @param nrpts
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getImmunizations(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nrpts")
        String nrpts);

    /**
     * Get patient's outpatient prescription profile.
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getOutpatientRxProfile();

    /**
     * Get patient's meds administation history.
     * 
     * @param fromDate
     * @param toDate
     * @param nrpts
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getMedsAdminHx(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nrpts")
        String nrpts);

    /**
     * Get patient's meds administation log.
     * 
     * @param fromDate
     * @param toDate
     * @param nrpts
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getMedsAdminLog(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nrpts")
        String nrpts);

    /**
     * Get patient's chem/hem lab results.
     * 
     * @param fromDate
     * @param toDate
     * @param nrpts
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedChemHemRptArrays
     */
    @WebMethod
    @WebResult(name = "TaggedChemHemRptArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedChemHemRptArrays getChemHemReports(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nrpts")
        String nrpts);

    /**
     * Get patient's chem/hem lab results. Use 0 for number of results to retrieve all results for the time period.
     * 
     * @param fromDate
     * @param toDate
     * @param nrpts
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedChemHemRptArrays
     */
    @WebMethod
    @WebResult(name = "TaggedChemHemRptArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedChemHemRptArrays getChemHemReportsSimple(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nrpts")
        String nrpts);

    /**
     * Get patient's Cytology lab results.
     * 
     * @param fromDate
     * @param toDate
     * @param nrpts
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedCytologyRptArrays
     */
    @WebMethod
    @WebResult(name = "TaggedCytologyRptArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedCytologyRptArrays getCytologyReports(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nrpts")
        String nrpts);

    /**
     * Get patient's microbiology lab results.
     * 
     * @param fromDate
     * @param toDate
     * @param nrpts
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedMicrobiologyRptArrays
     */
    @WebMethod
    @WebResult(name = "TaggedMicrobiologyRptArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedMicrobiologyRptArrays getMicrobiologyReports(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nrpts")
        String nrpts);

    /**
     * Get patient's surgical pathology lab results.
     * 
     * @param fromDate
     * @param toDate
     * @param nrpts
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedSurgicalPathologyRptArrays
     */
    @WebMethod
    @WebResult(name = "TaggedSurgicalPathologyRptArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedSurgicalPathologyRptArrays getSurgicalPathologyReports(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nrpts")
        String nrpts);

    /**
     * Get patient's blood availability reports.
     * 
     * @param fromDate
     * @param toDate
     * @param nrpts
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getBloodAvailabilityReports(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nrpts")
        String nrpts);

    /**
     * Get patient's blood transfusion reports.
     * 
     * @param fromDate
     * @param toDate
     * @param nrpts
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getBloodTransfusionReports(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nrpts")
        String nrpts);

    /**
     * Get patient's blood bank reports.
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getBloodBankReports();

    /**
     * Get patient's electron microscopy reports.
     * 
     * @param fromDate
     * @param toDate
     * @param nrpts
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getElectronMicroscopyReports(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nrpts")
        String nrpts);

    /**
     * Get patient's cytopathology reports.
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getCytopathologyReports();

    /**
     * Get patient's autopsy reports.
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getAutopsyReports();

    /**
     * Get outpatient encounters from all connected VistAs.
     * 
     * @param fromDate
     * @param toDate
     * @param nrpts
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getOutpatientEncounterReports(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nrpts")
        String nrpts);

    /**
     * Get admission summaries from all connected VistAs.
     * 
     * @param fromDate
     * @param toDate
     * @param nrpts
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getAdmissionsReports(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nrpts")
        String nrpts);

    /**
     * Get ADT reports from all connected VistAs.
     * 
     * @param fromDate
     * @param toDate
     * @param nrpts
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getExpandedAdtReports(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nrpts")
        String nrpts);

    /**
     * Get discharge diagnosis from all connected VistAs.
     * 
     * @param fromDate
     * @param toDate
     * @param nrpts
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getDischargeDiagnosisReports(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nrpts")
        String nrpts);

    /**
     * Get discharge reports from all connected VistAs.
     * 
     * @param fromDate
     * @param toDate
     * @param nrpts
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getDischargesReports(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nrpts")
        String nrpts);

    /**
     * Get transfer reports from all connected VistAs.
     * 
     * @param fromDate
     * @param toDate
     * @param nrpts
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getTransfersReports(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nrpts")
        String nrpts);

    /**
     * Get future clinic visits from all connected VistAs.
     * 
     * @param fromDate
     * @param toDate
     * @param nrpts
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getFutureClinicVisitsReports(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nrpts")
        String nrpts);

    /**
     * Get past clinic visits from all connected VistAs.
     * 
     * @param fromDate
     * @param toDate
     * @param nrpts
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getPastClinicVisitsReports(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nrpts")
        String nrpts);

    /**
     * Get treating specialty from all connected VistAs.
     * 
     * @param fromDate
     * @param toDate
     * @param nrpts
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getTreatingSpecialtyReports(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nrpts")
        String nrpts);

    /**
     * Get C&P reports from all connected VistAs.
     * 
     * @param fromDate
     * @param toDate
     * @param nrpts
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getCompAndPenReports(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nrpts")
        String nrpts);

    /**
     * Get care team from all connected VistAs.
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getCareTeamReports();

    /**
     * Get ICD procedure reports from all connected VistAs.
     * 
     * @param fromDate
     * @param toDate
     * @param nrpts
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedIcdRptArrays
     */
    @WebMethod
    @WebResult(name = "TaggedIcdRptArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedIcdRptArrays getIcdProceduresReports(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nrpts")
        String nrpts);

    /**
     * Get ICD surgery reports from all connected VistAs.
     * 
     * @param fromDate
     * @param toDate
     * @param nrpts
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedIcdRptArrays
     */
    @WebMethod
    @WebResult(name = "TaggedIcdRptArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedIcdRptArrays getIcdSurgeryReports(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nrpts")
        String nrpts);

    /**
     * 
     * @param direction
     * @param target
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getNoteTitles(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "target")
        String target,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "direction")
        String direction);

    /**
     * 
     * @param direction
     * @param target
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedHospitalLocationArray
     */
    @WebMethod
    @WebResult(name = "TaggedHospitalLocationArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedHospitalLocationArray getHospitalLocations(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "target")
        String target,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "direction")
        String direction);

    /**
     * 
     * @param accessionNumber
     * @param ssn
     * @return
     *     returns gov.va.medora.mdws.emrsvc.RadiologyReportTO
     */
    @WebMethod
    @WebResult(name = "RadiologyReportTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public RadiologyReportTO getImagingReport(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "SSN")
        String ssn,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "accessionNumber")
        String accessionNumber);

    /**
     * Write a simple, by policy order to a single VistA
     * 
     * @param startDate
     * @param esig
     * @param providerDUZ
     * @param orderIEN
     * @param locationIEN
     * @return
     *     returns gov.va.medora.mdws.emrsvc.OrderTO
     */
    @WebMethod
    @WebResult(name = "OrderTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public OrderTO writeSimpleOrderByPolicy(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "providerDUZ")
        String providerDUZ,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "esig")
        String esig,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "locationIEN")
        String locationIEN,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "orderIEN")
        String orderIEN,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "startDate")
        String startDate);

    /**
     * Validate electronic signature
     * 
     * @param esig
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TextTO
     */
    @WebMethod
    @WebResult(name = "TextTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TextTO isValidEsig(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "esig")
        String esig);

    /**
     * Make a patient inquiry call (address, contact numbers, NOK, etc. information)
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TextTO
     */
    @WebMethod
    @WebResult(name = "TextTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TextTO patientInquiry();

    /**
     * Get a list of hospital wards
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedHospitalLocationArray
     */
    @WebMethod
    @WebResult(name = "TaggedHospitalLocationArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedHospitalLocationArray getWards();

    /**
     * Get a list of patients by ward
     * 
     * @param wardId
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedPatientArray
     */
    @WebMethod
    @WebResult(name = "TaggedPatientArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedPatientArray getPatientsByWard(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "wardId")
        String wardId);

    /**
     * Get a list of hospital clinics
     * 
     * @param target
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedHospitalLocationArray
     */
    @WebMethod
    @WebResult(name = "TaggedHospitalLocationArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedHospitalLocationArray getClinics(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "target")
        String target);

    /**
     * Get a list of patients by clinic
     * 
     * @param clinicId
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedPatientArray
     */
    @WebMethod
    @WebResult(name = "TaggedPatientArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedPatientArray getPatientsByClinic(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "clinicId")
        String clinicId);

    /**
     * Get the list of specialties
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedText
     */
    @WebMethod
    @WebResult(name = "TaggedText", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedText getSpecialties();

    /**
     * Get a list of patients by specialty
     * 
     * @param specialtyId
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedPatientArray
     */
    @WebMethod
    @WebResult(name = "TaggedPatientArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedPatientArray getPatientsBySpecialty(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "specialtyId")
        String specialtyId);

    /**
     * Get the list of teams
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedText
     */
    @WebMethod
    @WebResult(name = "TaggedText", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedText getTeams();

    /**
     * Get a list of patients by team
     * 
     * @param teamId
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedPatientArray
     */
    @WebMethod
    @WebResult(name = "TaggedPatientArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedPatientArray getPatientsByTeam(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "teamId")
        String teamId);

    /**
     * Get a list of patients by provider
     * 
     * @param duz
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedPatientArray
     */
    @WebMethod
    @WebResult(name = "TaggedPatientArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedPatientArray getPatientsByProvider(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "duz")
        String duz);

    /**
     * Get selected patient's admissions
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedInpatientStayArray
     */
    @WebMethod
    @WebResult(name = "TaggedInpatientStayArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedInpatientStayArray getAdmissions();

    /**
     * Get a VistA's hospital locations (clinics, etc.).
     * 
     * @param direction
     * @param target
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedHospitalLocationArray
     */
    @WebMethod
    @WebResult(name = "TaggedHospitalLocationArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedHospitalLocationArray getLocations(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "target")
        String target,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "direction")
        String direction);

    /**
     * Get patient record flag actions.
     * 
     * @param noteDefinitionIEN
     * @return
     *     returns gov.va.medora.mdws.emrsvc.PatientRecordFlagArray
     */
    @WebMethod
    @WebResult(name = "PatientRecordFlagArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public PatientRecordFlagArray getPrfNoteActions(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "noteDefinitionIEN")
        String noteDefinitionIEN);

    /**
     * Get selected patient's visits
     * 
     * @param fromDate
     * @param toDate
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedVisitArray
     */
    @WebMethod
    @WebResult(name = "TaggedVisitArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedVisitArray getVisits(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fromDate")
        String fromDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "toDate")
        String toDate);

    /**
     * Is given note a consult note?
     * 
     * @param noteDefinitionIEN
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TextTO
     */
    @WebMethod
    @WebResult(name = "TextTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TextTO isConsultNote(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "noteDefinitionIEN")
        String noteDefinitionIEN);

    /**
     * Is cosigner required for this user/author pair?
     * 
     * @param noteDefinitionIEN
     * @param authorDUZ
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TextTO
     */
    @WebMethod
    @WebResult(name = "TextTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TextTO isCosignerRequired(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "noteDefinitionIEN")
        String noteDefinitionIEN,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "authorDUZ")
        String authorDUZ);

    /**
     * Is given note a surgery note?
     * 
     * @param noteDefinitionIEN
     * @param visitString
     * @param noteTitle
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedText
     */
    @WebMethod
    @WebResult(name = "TaggedText", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedText isOneVisitNote(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "noteDefinitionIEN")
        String noteDefinitionIEN,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "noteTitle")
        String noteTitle,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "visitString")
        String visitString);

    /**
     * Is given note a PRF note?
     * 
     * @param noteDefinitionIEN
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TextTO
     */
    @WebMethod
    @WebResult(name = "TextTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TextTO isPrfNote(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "noteDefinitionIEN")
        String noteDefinitionIEN);

    /**
     * Is given note a surgery note?
     * 
     * @param noteDefinitionIEN
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedText
     */
    @WebMethod
    @WebResult(name = "TaggedText", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedText isSurgeryNote(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "noteDefinitionIEN")
        String noteDefinitionIEN);

    /**
     * Write a note.
     * 
     * @param authorDUZ
     * @param consultIEN
     * @param text
     * @param prfIEN
     * @param titleIEN
     * @param encounterString
     * @param cosignerDUZ
     * @return
     *     returns gov.va.medora.mdws.emrsvc.NoteResultTO
     */
    @WebMethod
    @WebResult(name = "NoteResultTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public NoteResultTO writeNote(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "titleIEN")
        String titleIEN,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "encounterString")
        String encounterString,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "text")
        String text,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "authorDUZ")
        String authorDUZ,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "cosignerDUZ")
        String cosignerDUZ,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "consultIEN")
        String consultIEN,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "prfIEN")
        String prfIEN);

    /**
     * Sign a note.
     * 
     * @param esig
     * @param noteIEN
     * @param userDUZ
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TextTO
     */
    @WebMethod
    @WebResult(name = "TextTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TextTO signNote(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "noteIEN")
        String noteIEN,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "userDUZ")
        String userDUZ,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "esig")
        String esig);

    /**
     * Close a note.
     * 
     * @param consultIEN
     * @param noteIEN
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TextTO
     */
    @WebMethod
    @WebResult(name = "TextTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TextTO closeNote(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "noteIEN")
        String noteIEN,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "consultIEN")
        String consultIEN);

    /**
     * Get a patient's demographics
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.PatientTO
     */
    @WebMethod
    @WebResult(name = "PatientTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public PatientTO getDemographics();

    /**
     * Find a patient in the MPI
     * 
     * @param ssn
     * @return
     *     returns gov.va.medora.mdws.emrsvc.PatientArray
     */
    @WebMethod
    @WebResult(name = "PatientArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public PatientArray mpiLookup(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "SSN")
        String ssn);

    /**
     * Find a patient in the NPT
     * 
     * @param ssn
     * @return
     *     returns gov.va.medora.mdws.emrsvc.PatientArray
     */
    @WebMethod
    @WebResult(name = "PatientArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public PatientArray nptLookup(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "SSN")
        String ssn);

    /**
     * Get a patient's orders
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedOrderArrays
     */
    @WebMethod
    @WebResult(name = "TaggedOrderArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedOrderArrays getAllOrders();

    /**
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TextArray
     */
    @WebMethod
    @WebResult(name = "TextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TextArray getReminderReportTemplates();

    /**
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getActiveReminderReports();

    /**
     * 
     * @param rptId
     * @return
     *     returns gov.va.medora.mdws.emrsvc.ReminderReportPatientListTO
     */
    @WebMethod
    @WebResult(name = "ReminderReportPatientListTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public ReminderReportPatientListTO getPatientListForReminderReport(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "rptId")
        String rptId);

    /**
     * 
     * @param pid
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedText
     */
    @WebMethod
    @WebResult(name = "TaggedText", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedText getPcpForPatient(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pid")
        String pid);

    /**
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getSitesForStation();

    /**
     * 
     * @param name
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getClinicsByName(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "name")
        String name);

    /**
     * 
     * @param name
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getOrderableItemsByName(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "name")
        String name);

    /**
     * 
     * @param orderableItemId
     * @param pid
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TextTO
     */
    @WebMethod
    @WebResult(name = "TextTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TextTO getOrderStatusForPatient(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "pid")
        String pid,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "orderableItemId")
        String orderableItemId);

    /**
     * 
     * @param displayGroupId
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getOrderDialogsForDisplayGroup(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "displayGroupId")
        String displayGroupId);

    /**
     * 
     * @param dialogId
     * @return
     *     returns gov.va.medora.mdws.emrsvc.OrderDialogItemArray
     */
    @WebMethod
    @WebResult(name = "OrderDialogItemArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public OrderDialogItemArray getOrderDialogItems(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "dialogId")
        String dialogId);

    /**
     * 
     * @param optionName
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getUsersWithOption(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "optionName")
        String optionName);

    /**
     * 
     * @param uid
     * @param permissionName
     * @return
     *     returns gov.va.medora.mdws.emrsvc.BoolTO
     */
    @WebMethod
    @WebResult(name = "BoolTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public BoolTO userHasPermission(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "uid")
        String uid,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "permissionName")
        String permissionName);

    /**
     * 
     * @param uid
     * @return
     *     returns gov.va.medora.mdws.emrsvc.UserSecurityKeyArray
     */
    @WebMethod
    @WebResult(name = "UserSecurityKeyArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public UserSecurityKeyArray getUserSecurityKeys(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "uid")
        String uid);

    /**
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedMentalHealthInstrumentAdministrationArrays
     */
    @WebMethod
    @WebResult(name = "TaggedMentalHealthInstrumentAdministrationArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedMentalHealthInstrumentAdministrationArrays getMentalHealthInstrumentsForPatient();

    /**
     * 
     * @param sitecode
     * @param administrationId
     * @return
     *     returns gov.va.medora.mdws.emrsvc.MentalHealthInstrumentResultSetTO
     */
    @WebMethod
    @WebResult(name = "MentalHealthInstrumentResultSetTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public MentalHealthInstrumentResultSetTO getMentalHealthInstrumentResultSet(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "sitecode")
        String sitecode,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "administrationId")
        String administrationId);

    /**
     * 
     * @param types
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TaggedTextArray
     */
    @WebMethod
    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TaggedTextArray getNhinData(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "types")
        String types);

    /**
     * Get MDWS Version
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public String getVersion();

    /**
     * Add a data source for this session
     * 
     * @param region
     * @param port
     * @param id
     * @param protocol
     * @param name
     * @param modality
     * @param datasource
     * @return
     *     returns gov.va.medora.mdws.emrsvc.SiteTO
     */
    @WebMethod
    @WebResult(name = "SiteTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public SiteTO addDataSource(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "id")
        String id,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "name")
        String name,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "datasource")
        String datasource,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "port")
        String port,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "modality")
        String modality,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "protocol")
        String protocol,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "region")
        String region);

    /**
     * Get current facade's version
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TextTO
     */
    @WebMethod
    @WebResult(name = "TextTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TextTO getFacadeVersion();

    /**
     * Set the current session's sites file
     * 
     * @param sitesFileName
     * @return
     *     returns gov.va.medora.mdws.emrsvc.SiteArray
     */
    @WebMethod
    @WebResult(name = "SiteArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public SiteArray setVha(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "sitesFileName")
        String sitesFileName);

    /**
     * Get the executed RPCs from the base Vista connection
     * 
     * @return
     *     returns gov.va.medora.mdws.emrsvc.TextArray
     */
    @WebMethod
    @WebResult(name = "TextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    public TextArray getRpcs();

}
